#!/bin/bash
echo "Downloading Doomicraft ... sit tight!"

git clone https://github.com/JpTanaka/Doomicraft
cd Doomicraft

git submodule init
git submodule update


echo "Making the build... "
cmake -B build
cd build

echo "Compiling... Almost there..."
make -j8

echo "All done!"
